name: Assign Label Action

on:
  issues:
    types: [assigned]
  pull_request:
    types: [assigned]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: Manoj-Paramsetti/greets-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label_1: 'assigned'
          issue_message: ''
          pr_message: ''
